class kibana::params {
  $ensure = 'present'

  $server_port = 5601
  $server_host = '127.0.0.1'
  $server_basePath = ''
  $server_maxPayloadBytes = 1048576
  $elasticsearch_url = 'http://localhost:9200'
  $elasticsearch_preserveHost = true
  $kibana_index = '.kibana'
  $kibana_defaultAppId = 'discover'
  $elasticsearch_username = undef
  $elasticsearch_password = undef
  $server_ssl_enable = false
  $server_ssl_cert = "${::settings::ssldir}/certs/${::clientcert}.pem"
  $server_ssl_key = "${::settings::ssldir}/private_keys/${::clientcert}.pem"
  $elasticsearch_ssl_enable = false
  $elasticsearch_ssl_cert = "${::settings::ssldir}/certs/${::clientcert}.pem"
  $elasticsearch_ssl_key = "${::settings::ssldir}/private_keys/${::clientcert}.pem"
  $elasticsearch_ssl_ca = "${::settings::ssldir}/certs/ca.pem"
  $elasticsearch_ssl_verify = true
  $elasticsearch_pingTimeout = 1500
  $elasticsearch_requestTimeout = 300000
  $elasticsearch_shardTimeout = 0
  $elasticsearch_startupTimeout = 5000
  $pid_file = '/var/run/kibana.pid'
  $logging_dest = 'stdout'
  $logging_silent = false
  $logging_quiet = false
  $logging_verbose = false
}
